version: "3.9"

services:
  frontend:
   build:
    context: ./frontend
    dockerfile: Dockerfile
   container_name: frontend_container
   ports:
    - "5173:5173"
   working_dir: /app
   volumes:
   - ./frontend:/app
      - frontend_node_modules:/app/node_modules
   depends_on:
    - backend
   command: ["npm", "run", "dev", "--", "--host"]
   


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "5000:5000"
    working_dir: /app
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      - mysql-db
    environment:
      DB_HOST: mysql-db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: todo_app
      DB_PORT: "3307"
    command: ["npm", "run", "dev"]

  mysql-db:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_app
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
  backend_node_modules:
  frontend_node_modules: