version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    depends_on:
      - backend
    command: ["npm", "run", "dev", "--", "--host"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    command: ["npm", "run", "dev"]
